### ISSUE TITLE
vertaisarviointi 1

### ISSUE THREAD

**Issue by LauraImmonen** [hurbios/gym-logger#2]
Sovelluksen auki saamiseksi oleviin ohjeisiin voisi lisätä, miten ensin tulisi kloonata repo ja tehdä sille hakemisto. 

Sovellus näyttää todella hienolta ja oli helppokäyttöinen. Se oli esteettisesti myös mielestäni hienosti tehty. Huomaa että olet tehnyt sovelluksia aikaisemminkin. Koodi oli helppolukuista ja näytti ammattimaiselta. 

Sovelluksessa huomasin kohdassa "add exercise" napin "presaved exercises" joka ei tehnyt mitään, sen voisi korjata tai poistaa. Myös kohdassa, jossa voi lisätä "work out result" voisi olla vaihtoehtona kirjata, kuinka monta rep ja set sai tehtyä, koska jos tekee esim. kehonpainoharjoituksia, ei tule käytettyä tuota kg kohtaa. Muuten sovellus oli mielestäni jo toimiva ja hyvin tehty.

**Comment by hurbios** [comment]
Kiitos hyvästä arvioinnista. Tein muutoksia tämän perusteella ja issuen tulevaisuutta varten kehonpainoharjoituksien tukemiseksi.

Lisäsin ohjeet repon kloonausta varten ja poistin ylimääräisen presaved exercises valikon. 
(presaved exercises oli dropdown menu jonka valinta antoi automaattisesti nimen inputtiin, muttei kuitenkaan sarjamääriä (sets) eikä toistomääriä (reps). Näin ollen tuon hyöty jäi vähäiseksi ja tosiaan varmaan parempi poistaa toiminnallisuus.

Ehdotus muokata sovellusta tulosten osalta niin että tulos voisi olla painon lisäksi myös vaihtoehtoisesti sarjamäärä ja toistomäärä kuullostaa hyvältä. Tämä voisinkin olla käytön kannalta varsin järkevää erilaisten käyttötapausten kattamiseksi. Koen kuitenkin kurssin tähtäävän MVP sovellukseen ja python flask & postgesql yhdistelmän osaamisen osoittamiseen joten tämä ominaisuus kuullostaisikin oikein hyvältä lisätä mahdolliseen kurssin jälkeiseen versioon 2.

- muutokset: https://github.com/hurbios/gym-logger/pull/3
- tulevaisuuden issue kehonpainoharjoittelun tukemiseksi: https://github.com/hurbios/gym-logger/issues/4

**Comment by hurbios** [comment]
Kiitos hyvästä arvioinnista. Tein muutoksia tämän perusteella ja issuen tulevaisuutta varten kehonpainoharjoituksien tukemiseksi.

Lisäsin ohjeet repon kloonausta varten ja poistin ylimääräisen presaved exercises valikon.
(presaved exercises oli dropdown menu jonka valinta antoi automaattisesti nimen inputtiin, muttei kuitenkaan sarjamääriä (sets) eikä toistomääriä (reps). Näin ollen tuon hyöty jäi vähäiseksi ja tosiaan varmaan parempi poistaa toiminnallisuus.

Ehdotus muokata sovellusta tulosten osalta niin että tulos voisi olla painon lisäksi myös vaihtoehtoisesti sarjamäärä ja toistomäärä kuullostaa hyvältä. Tämä voisinkin olla käytön kannalta varsin järkevää erilaisten käyttötapausten kattamiseksi. Koen kuitenkin kurssin tähtäävän MVP sovellukseen ja python flask & postgesql yhdistelmän osaamisen osoittamiseen joten tämä ominaisuus kuullostaisikin oikein hyvältä lisätä mahdolliseen kurssin jälkeiseen versioon 2.

muutokset: https://github.com/hurbios/gym-logger/pull/3
tulevaisuuden issue kehonpainoharjoittelun tukemiseksi: https://github.com/hurbios/gym-logger/issues/4
