### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by doomwall** [hurbios/gym-logger#5]
Tässä löytämiäni huomioita sovelluksestasi

- README oli rakennettu todella hyvin ja asennusohjeet loistavat
- Login toimii hyvin
- Rekisteröinti on toimiva
- Ohjelmien lisäys, muokkaus ja poistaminen pelittää upeasti
- Workoutin lisäyksessäkään ei mitään moittimista, hyvää työtä!
- Kaikinpuolin toimivat sivut ja erinomainen pohja sivustolle
- Ulkoasu oli toimiva ja hyvin rakennettu
- Koodi helposti luettavaa ja loogista
- Testitietokanta oli hyvä lisäys vertaisarviointia varten
- Error-viestejä en saanut näkyviin esim. tilanteessa jossa kirjoitin salasanan väärin tai yritin käydä sivustolla johon ei ollut oikeutta
- Rekisteröinti formissa ei ole juuri validointia, eli salasanaksi käy tällä hetkellä lyhyet ja heikot salasanat

Toimiva sovellus, jossa vain pieniä probleemia esimerkiksi error-palautteen kanssa ja rekisteröinti-formin validoinnin kanssa. Muuten tietokannat toimivat hyvin, ja sovelluksella luotuja kuntosali-ohjelmia oli helppo lisätä ja muokata. Hyvää työtä!

**Comment by hurbios** [comment]
Kiitos hyvästä palautteesta ja kehitysideoista. Lisäsin tämän perusteella kirjautumiseen error-viestin ja rekisteröitiin salasanarajoitteita. https://github.com/hurbios/gym-logger/pull/6
